---
- hosts: localhost
  connection: local

  vars:
    plugins:
      - maven-plugin
      - github
      - postbuildscript
      - postbuild-task
    jenkins_java_args: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
    jenkins_home: /var/lib/jenkins
    jenkins_hostname: 127.0.0.1
    jenkins_http_port: 8080
    jenkins_admin_username: admin
    jenkins_admin_password: admin
    jenkins_jar_location: /home/vagrant/jenkins-cli.jar
    jenkins_default_file: /etc/default/jenkins
    jenkins_params:
      url_username: "{{ jenkins_admin_username }}"
      validate_certs: no
    # update file path 
    groovy_file_path: /vagrant_data/JenkinsSetup

  tasks:
      - name: add jenkins public key
        become: yes
        become_method: sudo
        apt_key:
          url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
          state: present

      - name: add jenkins to trusted sources list
        become: yes
        become_method: sudo
        apt_repository:
          repo: 'deb http://pkg.jenkins-ci.org/debian binary/'
          state: present

      - name: Update apt package
        become: yes
        become_method: sudo
        apt:
          update_cache: yes

      - name: Install Jenkins
        become: yes
        become_method: sudo
        apt: pkg= {{ item }} state=present install_recommends=yes
        with_items:
        - jenkins
        - maven

      - name: Configure JVM Args
        become: yes
        become_method: sudo
        lineinfile:
          dest: /etc/default/jenkins
          regexp: '^JAVA_ARGS='
          line: "{{ jenkins_java_args }}"
    
      - name: Create Groovy Script directory
        become: yes
        become_method: sudo
        file:
          path: "{{ jenkins_home }}/init.groovy.d"
          state: directory
          mode: 0755

      - name: Copy Groovy Script for default user creation
        become: yes
        become_method: sudo
        template:
          force: yes
          src: "{{ groovy_file_path }}/jenkins_script.groovy.j2"
          dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
          mode: 0755

      - name: Restart jenkins
        become: yes
        become_method: sudo
        service:
          name: jenkins
          state: restarted

      - name: Wait while Jenkins starts
        wait_for: port={{ jenkins_http_port }} delay=30

      - name: Remove Groovy Script
        become: yes
        become_method: sudo
        file:
          path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
          state: absent
       
      - name: Disable setup wizard
        jenkins_script:
          script: |
            import static jenkins.model.Jenkins.instance as jenkins
            import jenkins.install.InstallState
            if (!jenkins.installState.isSetupComplete()) {
              InstallState.INITIAL_SETUP_COMPLETED.initializeState()
            }
          user: "{{ jenkins_admin_username }}"
          password: "{{ jenkins_admin_password }}"

      - name: Get client JAR file
        become: yes
        become_method: sudo
        get_url:
          url: http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/jnlpJars/jenkins-cli.jar
          dest: /home/vagrant/
          owner: vagrant
          group: vagrant
          mode: u=rwx,g=r,o=r
          force: yes

      - name: Install Jenkins Plugins
        jenkins_plugin:
          name: "{{ item }}"
          params: "{{ jenkins_params }}"
          url_password: "{{ jenkins_admin_password }}"
          url: "http://{{jenkins_hostname}}:{{jenkins_http_port}}"
        with_items: "{{ plugins }}"

      - name: Restart Jenkins
        become: yes
        become_method: sudo
        service:
          name: jenkins
          state: restarted

      - name: Wait while Jenkins starts
        wait_for:
          host: "{{ jenkins_hostname }}"
          port: "{{ jenkins_http_port }}"
          delay: 30