---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    - jenkins_home: "/var/lib/jenkins"
    - jenkins_user: "jenkins"
    - admin_password: "admin"
    - admin_token: "7913bc559f169b4bcfc599360ce4d934"
    - home_dir: "/home/vagrant/jenkins"
    - jenkins_ip: 127.0.0.1
    - jenkins_port: 8080
  become: yes
  tasks:
    # INSTALL
    - name: install pip
      apt:
        name: "{{ item }}"
      with_items:
        - python-pip

#        - python3-jenkins
#        - python3-lxml
#        - python3-setuptools
    - name: install jenkins job builder
      pip:
        name: jenkins-job-builder
#    - name: install plugins
#      jenkins_plugin:
#        name: "{{ item }}"
#        url: "http://admin:{{ admin_password }}@{{ jenkins_ip }}:{{ jenkins_port }}"
#      with_items:
#        - git
#        - execute-shell
#    - name: restart jenkins
#      service:
#        name: jenkins
#        state: restarted

    # COPY JOBS
    - name: create jenkins_jobs folder
      file:
        path: "/etc/jenkins_jobs"
        state: directory
    - name: copy jenkins_jobs.ini template
      template:
        src: "{{ home_dir }}/templates/jenkins_jobs.ini.j2"
        dest: "/etc/jenkins_jobs/jenkins_jobs.ini"

    # CONFIGURE & BUILD
    - name: copy jobs
      copy:
        src: "{{ home_dir }}/jobs/"
        dest: "{{ jenkins_home }}/jobs/"
        directory_mode: yes
        mode: 0755
    - name: configure jobs
      shell: "jenkins-jobs update jobs"
      args:
        chdir: "{{ jenkins_home }}"
      register: output

    - name: say what
      debug:
        var: output
