---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  become_method: sudo
  tasks:
  
  - name: Install latest version of maven, mysql and java
    apt: pkg={{ item }} state=installed update_cache=true cache_valid_time=36000
    with_items:
    - mysql-server 
  
  - name: edit my.cnf file
    lineinfile:
      path: /etc/mysql/my.cnf
      line: "{{ item }}"
    with_items:
    - "[mysqld]"
    - "skip-grant-tables"
  
  - name: restart mysql
    service:
      name: mysql
      state: restarted

